[package]
name = "neurospider-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
foundationdb = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
