[package]
name = "neurospider-security"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = { workspace = true }
ed25519-dalek = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
zeroize = { workspace = true }
serde = { workspace = true }
